name: CI/CD
run-name: ${{ github.actor }} ran CI/CD

on:
  push:
    branches: [ main ]

jobs:
  run-controller:
    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      CLEARML_CONFIG_FILE: clearml.conf
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      COMMIT_ID: ${{ github.event.pull_request.head.sha }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip clearml pandas numpy matplotlib seaborn "tensorflow<2.11" keras tqdm scikit-learn
        - name: Start the task
          id: launch_task
          run: |
            python Controller
